import Header from '@/components/layout/Header'
import { Rubik } from 'next/font/google'
import './globals.css'
import Footer from '@/components/layout/Footer'

const rubic = Rubik({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--rubic'
}
)

export const metadata = {
  title: 'InfoSwipe',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  // used to load the font
  // eslint-disable-next-line @typescript-eslint/no-unused-expressions
  rubic.className
  return (
    <html lang='es'>
      <head>
        <link rel='apple-touch-icon' sizes='180x180' href='/apple-touch-icon.png' />
        <link rel='icon' type='image/png' sizes='32x32' href='/favicon-32x32.png' />
        <link rel='icon' type='image/png' sizes='16x16' href='/favicon-16x16.png' />
        <link rel='manifest' href='/site.webmanifest' />
        <link rel='mask-icon' href='/safari-pinned-tab.svg' color='#5bbad5' />
        <meta name='msapplication-TileColor' content='#ffffff' />
        <meta name='theme-color' content='#ffffff' />
      </head>
      <body className='flex flex-col min-h-screen min-w-screen w-full h-full bg-[#f5f5f5]'>
        <Header />
        <main className='flex-1 flex flex-col min-h-[calc(100vh_-_85px)] w-full items-center p-3 max-w-4xl bg-white mx-auto shadow-custom'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
